# Generated by Django 4.0.3 on 2022-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=12)),
                ('flat', models.IntegerField()),
                ('street', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=12)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
